# Generated by Django 4.1.4 on 2023-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0010_remove_guide_gp'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Link', models.TextField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('im', models.ImageField(default='eventp.png', upload_to='Images/Events/')),
            ],
        ),
    ]
