# Generated by Django 4.1.6 on 2023-02-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0011_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='im',
            field=models.ImageField(default='Images/eventp.png', upload_to='Images/Events/'),
        ),
    ]
